# Aravind Sai Oggu

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("digit_svm.csv")

In [4]:
df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [5]:
x = df.iloc[:, 1:].values
y = df.iloc[:, 0].values

In [6]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [7]:
y

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.01,random_state=0)

In [10]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
y_test

array([3, 6, 9, 5, 6, 5, 6, 0, 0, 1, 7, 1, 5, 7, 8, 1, 1, 5, 9, 6, 9, 2,
       2, 8, 4, 6, 2, 5, 4, 4, 8, 2, 8, 9, 3, 8, 4, 5, 2, 7, 6, 3, 1, 7,
       9, 7, 4, 2, 5, 0, 0, 3, 9, 8, 5, 1, 3, 1, 3, 5, 4, 6, 4, 7, 8, 2,
       4, 2, 1, 2, 0, 0, 6, 5, 7, 0, 9, 1, 9, 2, 0, 4, 3, 3, 2, 8, 7, 6,
       5, 8, 7, 9, 2, 8, 8, 4, 9, 1, 5, 1, 6, 5, 7, 9, 1, 2, 9, 4, 0, 4,
       5, 8, 1, 3, 1, 7, 2, 5, 7, 3, 3, 7, 5, 0, 9, 3, 6, 6, 3, 3, 5, 0,
       9, 2, 6, 0, 4, 3, 1, 7, 4, 1, 1, 9, 8, 6, 3, 7, 0, 4, 7, 3, 9, 1,
       7, 3, 1, 5, 0, 9, 9, 1, 7, 2, 1, 1, 5, 1, 5, 6, 9, 8, 3, 4, 3, 7,
       6, 4, 9, 1, 6, 4, 4, 3, 7, 2, 9, 3, 1, 1, 5, 7, 0, 0, 5, 1, 8, 6,
       2, 9, 8, 5, 3, 7, 2, 6, 9, 5, 0, 3, 3, 2, 8, 6, 1, 7, 4, 8, 8, 9,
       1, 4, 0, 1, 4, 1, 5, 2, 5, 0, 9, 2, 8, 9, 1, 4, 7, 0, 0, 5, 6, 0,
       1, 5, 7, 7, 2, 4, 2, 1, 5, 6, 8, 2, 9, 1, 6, 1, 5, 6, 2, 2, 4, 0,
       4, 9, 5, 4, 9, 6, 6, 4, 9, 4, 8, 7, 4, 4, 2, 4, 8, 8, 6, 8, 6, 1,
       2, 7, 3, 8, 7, 8, 4, 1, 0, 7, 2, 0, 6, 5, 5,

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc=StandardScaler()

In [14]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [15]:
from sklearn.svm import SVC

In [16]:
clf = SVC(kernel="linear", random_state=0)

In [17]:
clf.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [18]:
pred_y = clf.predict(x_test)

In [19]:
pred_y

array([3, 6, 9, 5, 6, 4, 6, 0, 0, 1, 7, 1, 5, 7, 8, 1, 1, 5, 9, 6, 9, 2,
       2, 8, 4, 6, 2, 5, 4, 4, 8, 2, 8, 9, 3, 8, 4, 5, 2, 7, 6, 3, 1, 7,
       9, 7, 4, 2, 5, 0, 0, 3, 9, 8, 5, 1, 3, 1, 3, 5, 4, 6, 4, 3, 8, 2,
       4, 8, 1, 2, 0, 0, 6, 5, 7, 0, 9, 1, 9, 2, 0, 4, 3, 3, 2, 8, 7, 2,
       5, 8, 7, 9, 2, 8, 8, 4, 9, 1, 5, 1, 6, 5, 7, 9, 1, 2, 9, 4, 0, 4,
       5, 8, 1, 3, 1, 7, 2, 5, 7, 3, 3, 7, 5, 0, 9, 3, 6, 6, 3, 3, 6, 0,
       9, 2, 6, 0, 4, 2, 1, 7, 4, 1, 1, 9, 8, 6, 3, 7, 0, 4, 7, 3, 9, 1,
       7, 3, 1, 3, 0, 9, 9, 1, 7, 2, 1, 1, 5, 1, 5, 6, 9, 1, 1, 4, 3, 7,
       6, 4, 9, 1, 6, 4, 4, 3, 7, 2, 9, 3, 1, 1, 5, 7, 0, 0, 5, 1, 8, 6,
       2, 9, 1, 5, 3, 8, 2, 6, 9, 5, 0, 3, 5, 2, 8, 6, 1, 7, 8, 8, 8, 9,
       1, 4, 0, 1, 4, 1, 5, 2, 5, 0, 9, 2, 9, 9, 1, 4, 7, 0, 0, 5, 6, 0,
       1, 5, 7, 7, 2, 4, 2, 1, 5, 6, 8, 2, 9, 1, 6, 1, 5, 4, 2, 2, 4, 0,
       4, 9, 5, 4, 9, 6, 6, 4, 9, 4, 8, 7, 4, 4, 2, 4, 8, 5, 6, 8, 6, 1,
       2, 7, 3, 1, 7, 3, 4, 1, 0, 7, 2, 0, 6, 5, 5,

In [20]:
y_test

array([3, 6, 9, 5, 6, 5, 6, 0, 0, 1, 7, 1, 5, 7, 8, 1, 1, 5, 9, 6, 9, 2,
       2, 8, 4, 6, 2, 5, 4, 4, 8, 2, 8, 9, 3, 8, 4, 5, 2, 7, 6, 3, 1, 7,
       9, 7, 4, 2, 5, 0, 0, 3, 9, 8, 5, 1, 3, 1, 3, 5, 4, 6, 4, 7, 8, 2,
       4, 2, 1, 2, 0, 0, 6, 5, 7, 0, 9, 1, 9, 2, 0, 4, 3, 3, 2, 8, 7, 6,
       5, 8, 7, 9, 2, 8, 8, 4, 9, 1, 5, 1, 6, 5, 7, 9, 1, 2, 9, 4, 0, 4,
       5, 8, 1, 3, 1, 7, 2, 5, 7, 3, 3, 7, 5, 0, 9, 3, 6, 6, 3, 3, 5, 0,
       9, 2, 6, 0, 4, 3, 1, 7, 4, 1, 1, 9, 8, 6, 3, 7, 0, 4, 7, 3, 9, 1,
       7, 3, 1, 5, 0, 9, 9, 1, 7, 2, 1, 1, 5, 1, 5, 6, 9, 8, 3, 4, 3, 7,
       6, 4, 9, 1, 6, 4, 4, 3, 7, 2, 9, 3, 1, 1, 5, 7, 0, 0, 5, 1, 8, 6,
       2, 9, 8, 5, 3, 7, 2, 6, 9, 5, 0, 3, 3, 2, 8, 6, 1, 7, 4, 8, 8, 9,
       1, 4, 0, 1, 4, 1, 5, 2, 5, 0, 9, 2, 8, 9, 1, 4, 7, 0, 0, 5, 6, 0,
       1, 5, 7, 7, 2, 4, 2, 1, 5, 6, 8, 2, 9, 1, 6, 1, 5, 6, 2, 2, 4, 0,
       4, 9, 5, 4, 9, 6, 6, 4, 9, 4, 8, 7, 4, 4, 2, 4, 8, 8, 6, 8, 6, 1,
       2, 7, 3, 8, 7, 8, 4, 1, 0, 7, 2, 0, 6, 5, 5,

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [22]:
confusion_matrix(y_test, pred_y)

array([[39,  0,  0,  0,  1,  0,  1,  0,  0,  0],
       [ 0, 49,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 36,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1,  1, 38,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 42,  0,  1,  0,  1,  0],
       [ 0,  0,  0,  1,  1, 43,  1,  0,  0,  0],
       [ 0,  0,  2,  0,  1,  0, 42,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0, 41,  1,  0],
       [ 0,  3,  0,  1,  0,  1,  0,  0, 30,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 38]], dtype=int64)

In [23]:
accuracy_score(y_test, pred_y)

0.9476190476190476

In [24]:
clf1 = SVC(kernel="rbf", random_state=0)

In [25]:
clf1.fit(x_train, y_train)

SVC(random_state=0)

In [26]:
pred_y1 = clf1.predict(x_test)

In [27]:
pred_y1

array([3, 6, 9, 5, 6, 5, 6, 0, 0, 1, 7, 1, 5, 7, 8, 1, 1, 5, 9, 6, 9, 2,
       2, 8, 4, 6, 2, 5, 4, 4, 8, 2, 8, 9, 3, 8, 4, 5, 2, 7, 6, 3, 1, 7,
       9, 7, 4, 2, 5, 0, 0, 3, 8, 8, 5, 1, 3, 1, 3, 5, 4, 6, 9, 7, 8, 2,
       4, 8, 1, 2, 0, 0, 6, 5, 7, 0, 9, 1, 9, 2, 0, 4, 3, 3, 2, 8, 7, 2,
       5, 8, 7, 9, 2, 8, 8, 4, 9, 1, 5, 1, 6, 5, 7, 9, 1, 2, 9, 4, 0, 4,
       5, 8, 1, 3, 1, 7, 2, 5, 7, 3, 3, 7, 5, 0, 9, 3, 6, 6, 3, 3, 5, 0,
       9, 2, 6, 0, 4, 3, 1, 7, 4, 1, 1, 9, 8, 6, 3, 7, 0, 4, 7, 3, 9, 1,
       7, 3, 1, 5, 0, 9, 9, 1, 7, 2, 1, 1, 5, 1, 5, 6, 9, 8, 3, 4, 3, 7,
       6, 4, 9, 1, 6, 4, 4, 3, 7, 2, 9, 3, 1, 1, 5, 7, 0, 0, 5, 1, 8, 6,
       2, 9, 8, 5, 3, 8, 2, 6, 9, 5, 0, 3, 3, 2, 8, 6, 1, 7, 9, 8, 8, 9,
       1, 4, 0, 1, 4, 1, 5, 2, 5, 0, 9, 2, 8, 9, 1, 4, 7, 0, 0, 5, 6, 0,
       1, 5, 7, 7, 2, 4, 2, 1, 5, 6, 8, 2, 9, 1, 6, 1, 5, 6, 2, 2, 4, 0,
       4, 9, 5, 4, 9, 6, 6, 4, 9, 4, 8, 7, 4, 4, 2, 4, 8, 5, 6, 8, 6, 1,
       2, 7, 3, 8, 7, 8, 4, 1, 0, 7, 2, 0, 6, 5, 5,

In [28]:
y_test

array([3, 6, 9, 5, 6, 5, 6, 0, 0, 1, 7, 1, 5, 7, 8, 1, 1, 5, 9, 6, 9, 2,
       2, 8, 4, 6, 2, 5, 4, 4, 8, 2, 8, 9, 3, 8, 4, 5, 2, 7, 6, 3, 1, 7,
       9, 7, 4, 2, 5, 0, 0, 3, 9, 8, 5, 1, 3, 1, 3, 5, 4, 6, 4, 7, 8, 2,
       4, 2, 1, 2, 0, 0, 6, 5, 7, 0, 9, 1, 9, 2, 0, 4, 3, 3, 2, 8, 7, 6,
       5, 8, 7, 9, 2, 8, 8, 4, 9, 1, 5, 1, 6, 5, 7, 9, 1, 2, 9, 4, 0, 4,
       5, 8, 1, 3, 1, 7, 2, 5, 7, 3, 3, 7, 5, 0, 9, 3, 6, 6, 3, 3, 5, 0,
       9, 2, 6, 0, 4, 3, 1, 7, 4, 1, 1, 9, 8, 6, 3, 7, 0, 4, 7, 3, 9, 1,
       7, 3, 1, 5, 0, 9, 9, 1, 7, 2, 1, 1, 5, 1, 5, 6, 9, 8, 3, 4, 3, 7,
       6, 4, 9, 1, 6, 4, 4, 3, 7, 2, 9, 3, 1, 1, 5, 7, 0, 0, 5, 1, 8, 6,
       2, 9, 8, 5, 3, 7, 2, 6, 9, 5, 0, 3, 3, 2, 8, 6, 1, 7, 4, 8, 8, 9,
       1, 4, 0, 1, 4, 1, 5, 2, 5, 0, 9, 2, 8, 9, 1, 4, 7, 0, 0, 5, 6, 0,
       1, 5, 7, 7, 2, 4, 2, 1, 5, 6, 8, 2, 9, 1, 6, 1, 5, 6, 2, 2, 4, 0,
       4, 9, 5, 4, 9, 6, 6, 4, 9, 4, 8, 7, 4, 4, 2, 4, 8, 8, 6, 8, 6, 1,
       2, 7, 3, 8, 7, 8, 4, 1, 0, 7, 2, 0, 6, 5, 5,

In [29]:
confusion_matrix(y_test, pred_y1)

array([[40,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 49,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 36,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0, 41,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 41,  0,  1,  0,  0,  2],
       [ 0,  0,  0,  0,  0, 46,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0, 44,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 42,  1,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0, 35,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1, 37]], dtype=int64)

In [30]:
accuracy_score(y_test, pred_y1)

0.9785714285714285